defaults:
  - _self_

seed: 42
device: cuda:0
env: toy_2d
obs_dim: 1
action_dim: 2
denoising_steps: 20
horizon_steps: 1
cond_steps: 1
ft_denoising_steps: 0

logdir: logs_toy_2d/
dppo_path: ./dppo
train_dataset_path: ${dppo_path}/data/toy_2d/train.npz
base_policy_path: "${dppo_path}/log/toy-pretrain/toy_2d_pre_diffusion_mlp_ta1_td20/2026-01-01_18-57-00_42/checkpoint/state_5000.pt"


model:
  _target_: model.diffusion.diffusion_eval.DiffusionEval
  ft_denoising_steps: 0
  predict_epsilon: True
  denoised_clip_value: 1.0
  randn_clip_value: 3
  network_path: ${base_policy_path}
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 16
    mlp_dims: [512, 512, 512]
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: 20
  device: ${device}
  use_ddim: True
  ddim_steps: 8
  controllable_noise: False