defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: noise_opt_rm.noise_search.diffusion_loss.EvalDiffusionLoss

name: ${env}_pre_diffusion_mlp_ta${horizon_steps}_td${denoising_steps}_ddim-100steps_size4096
logdir: ./logs/robomimic-pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: ./dppo/log/robomimic-pretrain/transport/transport_pre_diffusion_mlp_ta8_td100_ddim-100steps_size2048/2025-04-21_08-40-08_47/checkpoint/state_3000.pt
train_dataset_path: ./dppo/log/robomimic/${env}/train.npz

seed: 50
device: cuda:0
env: transport
obs_dim: 59
action_dim: 14
denoising_steps: 100
horizon_steps: 8
cond_steps: 1

wandb:
  # entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: robomimic-diffusion-loss
  run: ${now:%H-%M-%S}_${name}

train:
  n_epochs: 3000
  batch_size: 256
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 3000
    warmup_steps: 100
    min_lr: 1e-5
  save_model_freq: 500

model:
  _target_: model.diffusion.diffusion_eval.DiffusionEval
  ft_denoising_steps: 0
  predict_epsilon: True
  denoised_clip_value: 1.0
  randn_clip_value: 3
  #
  network_path: ${base_policy_path}
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 32
    mlp_dims: [2048, 2048, 2048]
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: 100
  device: ${device}
  use_ddim: True
  ddim_steps: 8
  ddim_steps: 100
  controllable_noise: True

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}